I/flutter (11640): ♦♦♦♦ EntreprenantAddUpd -1
I/flutter (11640): ♦♦♦♦ INSERT DANS LE SERVEUR
I/flutter (11640): ♦♦♦♦ INSERT ODOO ♦♦♦♦
I/flutter (11640): ♦♦♦♦♦♦♦♦ INSERT ODOO toArrUpd {active: true, userId: 178, ref: , nature_piece: AUTRE, cni: NCni, state: draft, sexe: masculin, birthday: 1964-04-02, country_id: 44, lieu_naissance: lieu_naissance Lieu, profession: profession, terminal: , date_validite_piece: 2030-05-18, milieu_implantation: 1, nom_repondant: AAA OFF, fonction_repondant: 1, autre_fonction_repondant: , contact_1_repondant: 0712345678, contact_2_repondant: , email_repondant: , nom_prenom_dirigeant: AAA OFF, email_dirigeant: , name: AAA OFF, telephone_dirigeant: 0787654321, adresse_dirigeant: adresseDirigeant Adresse, qualite_dirigeant: 1, autre_qualite: , telephone_dirigeant_whatsapp: , cluster_id: 2, region_id: 2, departement_id: 3, sousprefecture_id: 5, commune_id: 5, localite_id: 47, zonerecensement_id: 0, quartier_id: 461, ilot_creation: -1, ImageBase64_PHOTO_ENTR: , ID3_templateBytes64: , ID3_croppedBytes64: }
I/flutter (11640): Database Connected!
I/flutter (11640): Database Connected!
I/flutter (11640):  O D O O 
I/flutter (11640): ERROR ODOO
I/flutter (11640): OdooException: {code: 200, message: Odoo Server Error, data: {name: odoo.exceptions.ValidationError, debug: Traceback (most recent call last):
I/flutter (11640):   File "/opt/id30_v2/odoo/odoo/service/model.py", line 98, in wrapper
I/flutter (11640):     return f(dbname, *args, **kwargs)
I/flutter (11640):   File "/opt/id30_v2/odoo/odoo/http.py", line 346, in checked_call
I/flutter (11640):     result = self.endpoint(*a, **kw)
I/flutter (11640):   File "/opt/id30_v2/odoo/odoo/http.py", line 948, in __call__
I/flutter (11640):     return self.method(*args, **kw)
I/flutter (11640):   File "/opt/id30_v2/odoo/odoo/http.py", line 526, in response_wrap
I/flutter (11640):     response = f(*args, **kw)
I/flutter (11640):   File "/opt/id30_v2/odoo/addons/web/controllers/main.py", line 959, in call_kw
I/flutter (11640):     return self._call_kw(model, method, args, kwargs)
I/flutter (11640):   File "/opt/id30_v2/odoo/addons/web/controllers/main.py", line 951, in _call_kw
I/flutter (11640):     return call_kw(request.env[model], method, args, kwargs)
I/flutter (11640):   File "/opt/id30_v2/odoo/odoo/api.py", line 758, in call_kw
I/flutter (11640):     return _call_kw_model_create(method, model, args, kwargs)
I/flutter (11640):   File "/opt/id30_v2/odoo/odoo/api.py", line 738, in _call_kw_model_create
I/flutter (11640):     result = method(recs, *args, **kwargs)
I/flutter (11640):   File "<decorator-gen-3>", line 2, in create
I/flutter (11640):   File "/opt/id30_v2/odoo/odoo/api.py", line 462, in _model_create_multi
I/flutter (11640):     return create(self, [arg])
I/flutter (11640):   File "/opt/id30_v2/odoo/odoo/models.py", line 3606, in create
I/flutter (11640):     records = self._create(data_list)
I/flutter (11640):   File "/opt/id30_v2/odoo/odoo/models.py", line 3706, in _create
I/flutter (11640):     cr.execute(query, params)
I/flutter (11640):   File "/opt/id30_v2/odoo/odoo/sql_db.py", line 148, in wrapper
I/flutter (11640):     return f(self, *args, **kwargs)
I/flutter (11640):   File "/opt/id30_v2/odoo/odoo/sql_db.py", line 225, in execute
I/flutter (11640):     res = self._obj.execute(query, params)
I/flutter (11640): psycopg2.IntegrityError: insert or update on table "innoving_entreprenant" violates foreign key constraint "innoving_entreprenant_zonerecensement_id_fkey"
I/flutter (11640): DETAIL:  Key (zonerecensement_id)=(0) is not present in table "innoving_zone_recensement".
I/flutter (11640): During handling of the above exception, another exception occurred:
I/flutter (11640): Traceback (most recent call last):
I/flutter (11640):   File "/opt/id30_v2/odoo/odoo/http.py", line 663, in _handle_exception
I/flutter (11640):     return super(JsonRequest, self)._handle_exception(exception)
I/flutter (11640):   File "/opt/id30_v2/odoo/odoo/http.py", line 321, in _handle_exception
I/flutter (11640):     raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
I/flutter (11640):   File "/opt/id30_v2/odoo/odoo/tools/pycompat.py", line 87, in reraise
I/flutter (11640):     raise value
I/flutter (11640):   File "/opt/id30_v2/odoo/odoo/http.py", line 705, in dispatch
I/flutter (11640):     result = self._call_function(**self.params)
I/flutter (11640):   File "/opt/id30_v2/odoo/odoo/http.py", line 353, in _call_function
I/flutter (11640):     return checked_call(self.db, *args, **kwargs)
I/flutter (11640):   File "/opt/id30_v2/odoo/odoo/service/model.py", line 158, in wrapper
I/flutter (11640):     raise ValidationError(msg)
I/flutter (11640): odoo.exceptions.ValidationError: ("L'opération ne peut pas être terminée:un autre modèle nécessite la suppression de l'enregistrement. Si possible, archivez-le à la place.\n\nModèle: Gestion des entreprenants (innoving.entreprenant), Contrainte: innoving_entreprenant_zonerecensement_id_fkey", None)
I/flutter (11640): , message: L'opération ne peut pas être terminée:un autre modèle nécessite la suppression de l'enregistrement. Si possible, archivez-le à la place.
I/flutter (11640): Modèle: Gestion des entreprenants (innoving.entreprenant), Contrainte: innoving_entreprenant_zonerecensement_id_fkey
I/flutter (11640): None, arguments: [L'opération ne peut pas être terminée:un autre modèle nécessite la suppression de l'enregistrement. Si possible, archivez-le à la place.
I/flutter (11640): Modèle: Gestion des entreprenants (innoving.entreprenant), Contrainte: innoving_entreprenant_zonerecensement_id_fkey, null], exception_type: validation_error}}
I/flutter (11640): ERROR ODOO